# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tatiana Barbone

description         : >-
  Hi! I'm Tatiana, a Computer Science Student at the University of San Diego.

baseurl: "" # the subpath of your site, e.g. /blog
github_username:  tatianabarbone
profile: https://avatars0.githubusercontent.com/u/52261336?s=460&amp;u=a6b8d2f53f3513783f3fdb65c0167340212dfae8&amp;v=4
author:
  name: Tatiana Barbone
  github: tatianabarbone
  linkedin: tatianabarbone

analytics:
  enabled: true
  google:
    tracking_id: UA-176701314-2

### Posts ###
permalink: /blog/:title

### Disqus ###

include:
  - _contact

# Build settings
# theme: portfolyou-jekyll-theme
remote_theme: YoussefRaafatNasry/portfolYOU
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
